Repository invitejay/UsainTurtleAlgo, pull requests merged in 2022-02, with the labels that each got.

#4 Add 백준 17952_0210
  invitejay/README.md
  invitejay/bj_17952.java
Labels: in progress, una confirm, jeong_confirm

#3 Add: Baekjoon 17952번 과제는 끝나지 않아!
  KwonYuna/Main_bj_17952.java
Labels: invitejay confirm, in progress, jeong_confirm

#5 bj_17952_과제는끝나지않아
  jhkang9820/Main_bj_17952_과제는끝나지않아.java
  jhkang9820/Main_bj_3986_좋은단어_study.java
Labels: invitejay confirm, in progress, una confirm

#7 Add: bj_2504 & README
  KwonYuna/Main_bj_10799.java
  KwonYuna/Main_bj_2504.java
  KwonYuna/Main_bj_3986.java
  KwonYuna/Main_bj_5430.java
  KwonYuna/README.md
Labels: invitejay confirm, platycodonv

#10 퍼스트 커밋 ^^
  tgb02087/README.md
Labels: invitejay confirm, in progress, una confirm, platycodonv

#6 Add bj_5430_AC
  invitejay/README.md
  invitejay/bj_10799.java
  invitejay/bj_3986.java
  invitejay/bj_5430.java
Labels: in progress, una confirm, jeong_confirm, platycodonv

#9 치즈🧀
  KwonYuna/Main_bj_2638.java
  KwonYuna/README.md
Labels: invitejay confirm, in progress, jeong_confirm

#12 Add: 02.21 문제들
  KwonYuna/Main_bj_10026.java
  KwonYuna/Main_bj_1012.java
  KwonYuna/Main_bj_15686.java
  KwonYuna/Main_bj_2206.java
  KwonYuna/Main_bj_2667.java
  KwonYuna/README.md
Labels: in progress
